# -*- coding: utf-8 -*-
"""codex_AIDE_fixed_3090_260320_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTDHRe8HcEnPyHhojtnOGBrQ1e9MaUTm

# Machine Learning Course 2026 HW2
The code scripts are from [aideml](https://github.com/WecoAI/aideml) project on github with some modifications.

AIDE: AI-Driven Exploration in the Space of Code

https://arxiv.org/pdf/2502.13138


<font color='red' size=6>Make a copy before running or editing the code.</font>

## Prerequisites
"""

# -----------------------------------------------------------------------
# MUST be the very first multiprocessing call, BEFORE torch / llama_cpp.
#
# Why forkserver?
#   - fork:       child inherits CUDA state → C-level crash / TypeError __del__
#   - spawn:      re-imports the whole file → re-loads Llama model → OOM / slow
#   - forkserver: Python starts one clean server process RIGHT NOW (before CUDA
#                 is ever touched). All future REPL children are forked from
#                 that clean server, so they never see CUDA → no crash.
# -----------------------------------------------------------------------
import multiprocessing
multiprocessing.set_start_method("forkserver", force=True)

# setting for empty pods

import ctypes

# 1. 解決 libgomp
ctypes.CDLL("/usr/lib/x86_64-linux-gnu/libgomp.so.1", mode=ctypes.RTLD_GLOBAL)

# 2. 魔法小技巧：讓 PyTorch 幫我們把 CUDA 全家桶一次載入
import torch

# 3. 接著再載入 llama_cpp
from llama_cpp import Llama
print("llama_cpp 載入成功！")

# install packages

# Download dataset


from llama_cpp import Llama

# myModel is declared at module level so child processes that re-import this
# file can reference the name without triggering a model load.
# The actual Llama(...) instantiation is guarded under __main__ below.
myModel = None

def generate_response(_model: Llama, _messages: str, temperature) -> str:
    """
    This function will inference the model with given messages.
    """
    _output = _model.create_chat_completion(
        messages=_messages,
        stop=["<|endoftext|>", "<|user|>", "<|observation|>"],  # GLM-4 stop tokens
        max_tokens=4096,    # This argument is how many tokens the model can generate.
        temperature=temperature,  # Fix: actually use the passed-in temperature
    )["choices"][0]["message"]["content"]

    return _output

if __name__ == "__main__":
    # Load model only in the main process.
    # forkserver/spawn child processes re-import this file with __name__ != "__main__"
    # so they skip this block entirely — no duplicate model load, no path error.
    myModel = Llama(
        "./GLM-4.7-Flash-UD-Q4_K_XL.gguf",
        verbose=True,
        n_gpu_layers=40,
        n_ctx=8192,
        n_batch=256,
    )
    # Quick sanity check
    _test_response = generate_response(myModel, [{"role": "user", "content": "Hi"}], temperature=0.0)
    print(_test_response)
    print("=" * 60)
    print("Model loaded OK, starting AIDE agent...")
    print("=" * 60)

"""## Functions

### Utils
"""

# Define a function to save the best solution and other good solutions to files.
def save_run(cfg, journal):
    # Retrieve and save the best found solution.
    best_node = journal.get_best_node(only_good=False)  # Get the best node.
    with open("best_solution_test.py", "w") as f:
        f.write(best_node.code)

    good_nodes = journal.get_good_nodes()  # Retrieve all good solution nodes.
    for i, node in enumerate(good_nodes):
        filename = f"good_solution_test_{i}.py"
        with open(filename, "w") as f:
            f.write(node.code)

"""### Interpreter (DO NOT MODIFY THIS CELL)"""

"""
DO NOT MODIFY THIS CELL

Python interpreter for executing code snippets and capturing their output.
"""


import logging
import os
import queue
import signal
import sys
import time
import traceback
import zipfile
from pathlib import Path
from shutil import rmtree
import shutil
from multiprocessing import Process, Queue
import multiprocessing
from typing import Hashable, cast

import humanize
import rich
import shutup
from rich.logging import RichHandler
from rich.syntax import Syntax
from dataclasses import dataclass
from dataclasses_json import DataClassJsonMixin


@dataclass
class ExecutionResult(DataClassJsonMixin):
    """
    Result of executing a code snippet in the interpreter.
    Contains the output, execution time, and exception information.
    """
    term_out: list[str]
    exec_time: float
    exc_type: str | None
    exc_info: dict | None = None
    exc_stack: list[tuple] | None = None

def exception_summary(e, exec_file_name):
    """Generates a string that summarizes an exception and its stack trace"""
    tb_lines = traceback.format_exception(e)
    # Combine the traceback lines into a single string, skipping lines that contain "importlib".
    tb_str = "".join(
        [
            line
            for line in tb_lines
            # if "importlib" not in line  # Filter out unwanted traceback lines.
        ]
    )

    exc_info = {}
    if hasattr(e, "args"):
        exc_info["args"] = [str(i) for i in e.args]  # Store the exception arguments as strings.
    for att in ["name", "msg", "obj"]:
        if hasattr(e, att):
            exc_info[att] = str(getattr(e, att))  # Store additional attributes if available.

    tb = traceback.extract_tb(e.__traceback__)  # Extract the traceback information.
    # Create a list of tuples for each frame in the traceback.
    exc_stack = [(t.filename, t.lineno, t.name, t.line) for t in tb]

    return tb_str, e.__class__.__name__, exc_info, exc_stack  # Return the formatted traceback and exception details.

# Define a class that redirects write operations to a multiprocessing queue.
class RedirectQueue:
    def __init__(self, queue, timeout=5):
        self.queue = queue  # Store the provided queue.
        self.timeout = timeout  # Set the timeout for queue operations.

    def write(self, msg):
        try:
            self.queue.put(msg, timeout=self.timeout)  # Attempt to put the message into the queue.
        except queue.Full:
            print("[Warning]:Queue write timed out")  # Warn if the queue is full and the write times out.

    def flush(self):
        pass  # No operation is needed for flushing in this context.

# Define the Interpreter class that simulates a standalone Python REPL.
class Interpreter:
    def __init__(
        self,
        timeout: int = 3600,  # Default timeout of 3600 seconds.
        agent_file_name: str = "runfile.py",  # Default file name for writing the agent's code.
    ):
        """
        Simulates a standalone Python REPL with an execution time limit.

        Args:
            timeout (int, optional): Timeout for each code execution step. Defaults to 3600.
            agent_file_name (str, optional): The name for the agent's code file. Defaults to "runfile.py".
        """
        self.timeout = min(timeout, 600)  # Cap at 10 min — ResNet18 training shouldn't take longer
        self.agent_file_name = agent_file_name  # Save the agent file name.
        self.process: Process = None  # Initialize the process attribute (will hold the child process).

    def child_proc_setup(self, result_outq: Queue) -> None:
        # Import shutup to suppress warnings in the child process.
        import shutup

        shutup.mute_warnings()  # Mute all warnings before further execution.

        # Fix: When using fork, the child inherits the llama_cpp Llama object.
        # On child exit, Llama.__del__ tries to free C-level GPU memory whose
        # function pointers are invalid in the forked child, causing:
        #   TypeError: 'NoneType' object is not callable
        # Solution: immediately null out the global model reference in the child
        # so __del__ has nothing to clean up.
        import sys as _sys
        _main = _sys.modules.get("__main__", None)
        if _main is not None and hasattr(_main, "myModel"):
            _main.myModel = None
        # Also null it in our own global scope if present
        glb = globals()
        if "myModel" in glb:
            glb["myModel"] = None

        # Redirect both stdout and stderr to the provided result queue.
        # trunk-ignore(mypy/assignment)
        sys.stdout = sys.stderr = RedirectQueue(result_outq)

    def _run_session(
        self, code_inq: Queue, result_outq: Queue, event_outq: Queue
    ) -> None:
        self.child_proc_setup(result_outq)  # Set up the child process for capturing output.

        global_scope: dict = {}  # Create an empty dictionary to serve as the global scope.
        while True:  # Continuously wait for new code to execute.
            code = code_inq.get()  # Retrieve code from the code input queue.
            with open(self.agent_file_name, "w") as f:  # Open the agent file for writing.
                f.write(code)  # Write the received code into the file.

            event_outq.put(("state:ready",))  # Signal that the interpreter is ready to execute the code.
            try:
                # Compile and execute the code within the global scope.
                exec(compile(code, self.agent_file_name, "exec"), global_scope)
            except BaseException as e:
                # If an exception occurs, generate a summary of the exception.
                tb_str, e_cls_name, exc_info, exc_stack = exception_summary(
                    e,
                    self.agent_file_name,
                )
                result_outq.put(tb_str)  # Put the traceback string into the result queue.
                if e_cls_name == "KeyboardInterrupt":
                    e_cls_name = "TimeoutError"  # Convert a KeyboardInterrupt into a TimeoutError.

                event_outq.put(("state:finished", e_cls_name, exc_info, exc_stack))  # Signal that execution finished with an error.
            else:
                event_outq.put(("state:finished", None, None, None))  # Signal that execution finished successfully.

            os.remove(self.agent_file_name)  # Remove the agent file after execution.

            result_outq.put("<|EOF|>")  # Put an EOF marker to indicate the end of output.

    def create_process(self) -> None:
        # Create three queues for communication with the child process:
        # - code_inq: for sending code to execute.
        # - result_outq: for receiving output from the execution.
        # - event_outq: for receiving state events (like ready and finished).
        # trunk-ignore(mypy/var-annotated)
        self.code_inq, self.result_outq, self.event_outq = Queue(), Queue(), Queue()
        #ctx = multiprocessing.get_context("spawn")
        ctx = multiprocessing.get_context("forkserver")  # safe with CUDA (see top of file)
        self.process = ctx.Process(
            target=self._run_session,  # Set the target function for the child process.
            args=(self.code_inq, self.result_outq, self.event_outq),  # Provide the necessary queues as arguments.
        )
        self.process.start()  # Start the child process.

    def cleanup_session(self):
        if self.process is None:  # If there is no process, nothing to clean up.
            return
        try:
            # Attempt to terminate the child process gracefully.
            self.process.terminate()  # Request the process to terminate.
            self.process.join(timeout=0.5)  # Wait for the process to finish with a 0.5-second timeout.

            if self.process.exitcode is None:  # If the process is still running,
                self.process.kill()  # Forcefully kill the process.
                self.process.join(timeout=0.5)  # Wait again for termination.

                if self.process.exitcode is None:  # If the process still hasn't terminated,
                    os.kill(self.process.pid, signal.SIGKILL)  # Send a SIGKILL signal.
        except Exception as e:
            print(f"Error during process cleanup: {e}")  # Print an error message if cleanup fails.
        finally:
            if self.process is not None:  # If the process exists,
                self.process.close()  # Close the process.
                self.process = None  # Reset the process attribute to None.

    def run(self, code: str, reset_session=True) -> ExecutionResult:
        """
        Execute the provided Python command in a separate process and return its output.

        Parameters:
            code (str): Python code to execute.
            reset_session (bool, optional): Whether to reset the interpreter session before executing the code. Defaults to True.

        Returns:
            ExecutionResult: Object containing the output and metadata of the code execution.
        """

        if reset_session:
            if self.process is not None:
                # If a previous process exists, clean it up before starting a new one.
                self.cleanup_session()
            self.create_process()  # Create a new child process.
        else:
            # For the first execution, reset_session must be True.
            assert self.process is not None

        assert self.process.is_alive()  # Ensure that the child process is running.

        self.code_inq.put(code)  # Send the code to the child process via the queue.

        # Wait for the child process to signal that it is ready.
        try:
            state = self.event_outq.get(timeout=30)  # Wait up to 30 seconds for the "state:ready" event.
        except queue.Empty:
            msg = "REPL child process failed to start execution"
            print(msg)  # Log a critical error if the process does not start.
            while not self.result_outq.empty():
                continue  # Drain the result queue.
            raise RuntimeError(msg) from None
        assert state[0] == "state:ready", state  # Verify that the received state is "state:ready".
        start_time = time.time()  # Record the start time of execution.

        child_in_overtime = False  # Flag to indicate if the child process has exceeded the timeout.

        while True:
            try:
                # Try to get the finished state from the child process.
                state = self.event_outq.get(timeout=10)  # Wait for the "state:finished" event.
                assert state[0] == "state:finished", state  # Ensure the state is "state:finished".
                exec_time = time.time() - start_time  # Calculate the total execution time.
                break  # Exit the loop if execution is finished.
            except queue.Empty:
                # If no event is received, check whether the process is still alive.
                if not child_in_overtime and not self.process.is_alive():
                    msg = "REPL child process died unexpectedly"
                    raise RuntimeError(msg) from None

                # If the process is still running, check if it has exceeded the timeout.
                if self.timeout is None:
                    continue
                running_time = time.time() - start_time  # Determine the running time.
                if running_time > self.timeout:
                    print(f"Execution exceeded timeout of {self.timeout}s")  # Log a timeout message.
                    os.kill(self.process.pid, signal.SIGINT)  # Send SIGINT to the process.
                    child_in_overtime = True  # Mark that the process is now in overtime.

                    # If the process exceeds the timeout by more than 5 seconds, force cleanup.
                    if running_time > self.timeout + 5:
                        self.cleanup_session()  # Clean up the child process.

                        state = (None, "TimeoutError", {}, [])  # Set state to indicate a timeout error.
                        exec_time = self.timeout  # Set the execution time to the timeout limit.
                        break

        output: list[str] = []  # Initialize a list to collect output lines.
        # Collect all output from the result queue until the EOF marker is encountered.
        start_collect = time.time()  # Record the start time for output collection.
        while not self.result_outq.empty() or not output or output[-1] != "<|EOF|>":
            try:
                # If output collection exceeds 5 seconds, log a warning.
                if time.time() - start_collect > 5:
                    print("[Warning]:Output collection timed out")
                    break
                output.append(self.result_outq.get(timeout=1))  # Append the next line of output.
            except queue.Empty:
                continue  # Continue if no output is available immediately.
        if output and output[-1] == "<|EOF|>":
            output.pop()  # Remove the EOF marker from the output list.

        # Extract exception information from the finished state.
        e_cls_name, exc_info, exc_stack = state[1:]

        if e_cls_name == "TimeoutError":
            # Append a timeout error message to the output if a timeout occurred.
            output.append(
                f"TimeoutError: Execution exceeded the time limit of {humanize.naturaldelta(self.timeout)}"
            )
        else:
            # Append the execution time information to the output.
            output.append(
                f"Execution time: {humanize.naturaldelta(exec_time)} seconds (time limit is {humanize.naturaldelta(self.timeout)})."
            )
        # Return an ExecutionResult object with all the execution details.
        return ExecutionResult(output, exec_time, e_cls_name, exc_info, exc_stack)

"""### Nodes

"""

import time
import uuid
from dataclasses import dataclass, field
from typing import Literal, Optional

from dataclasses_json import DataClassJsonMixin


@dataclass(eq=False)
class Node(DataClassJsonMixin):
    """A single node in the solution tree. Contains code, execution results, and evaluation information."""

    # ---- code & plan ----
    code: str
    plan: str = field(default=None, kw_only=True)  # type: ignore

    # ---- general attrs ----
    step: int = field(default=None, kw_only=True)  # type: ignore
    id: str = field(default_factory=lambda: uuid.uuid4().hex, kw_only=True)
    ctime: float = field(default_factory=lambda: time.time(), kw_only=True)
    parent: Optional["Node"] = field(default=None, kw_only=True)
    children: set["Node"] = field(default_factory=set, kw_only=True)

    # ---- execution info ----
    _term_out: list[str] = field(default=None, kw_only=True)  # type: ignore
    exec_time: float = field(default=None, kw_only=True)  # type: ignore
    exc_type: str | None = field(default=None, kw_only=True)
    exc_info: dict | None = field(default=None, kw_only=True)
    exc_stack: list[tuple] | None = field(default=None, kw_only=True)

    # ---- evaluation ----
    # post-execution result analysis (findings/feedback)
    analysis: str = field(default=None, kw_only=True)  # type: ignore
    metric: float = field(default=None, kw_only=True)  # type: ignore
    # whether the agent decided that the code is buggy
    # -> always True if exc_type is not None or no valid metric
    is_buggy: bool = field(default=None, kw_only=True)  # type: ignore

    def __post_init__(self) -> None:
        if self.parent is not None:
            self.parent.children.add(self)

    @property
    def stage_name(self) -> Literal["draft", "debug", "improve"]:
        """
        Return the stage of the node:
        - "stage" if the node is an initial solution draft
        - "debug" if the node is the result of a debugging step
        - "improve" if the node is the result of an improvement step
        """
        if self.parent is None:
            return "draft"
        return "debug" if self.parent.is_buggy else "improve"

    def absorb_exec_result(self, exec_result: ExecutionResult):
        """Absorb the result of executing the code from this node."""
        self._term_out = exec_result.term_out
        self.exec_time = exec_result.exec_time
        self.exc_type = exec_result.exc_type
        self.exc_info = exec_result.exc_info
        self.exc_stack = exec_result.exc_stack

    @property
    def term_out(self) -> str:
        """Get the terminal output of the code execution (after truncating it)."""
        return trim_long_string("".join(self._term_out))



    @property
    def is_leaf(self) -> bool:
        """Check if the node is a leaf node in the solution tree."""
        return not self.children

    def __eq__(self, other):
        return isinstance(other, Node) and self.id == other.id

    def __hash__(self):
        return hash(self.id)

    @property
    def debug_depth(self) -> int:
        """
        Return the number of consecutive debug steps from this node back to the root.
        Uses explicit None-safe check so is_buggy=None doesn't silently count as False.
        """
        if self.parent is None:
            return 0
        if self.parent.is_buggy:   # True only, not None
            return self.parent.debug_depth + 1
        return 0

    # (original version replaced — it called self.stage_name which treated
    #  is_buggy=None as False, causing debug_depth to return 0 too early)
    # @property
    # def debug_depth(self) -> int:
    #     if self.stage_name != "debug":
    #         return 0
    #     return self.parent.debug_depth + 1

"""### Tree"""

@dataclass
class Journal(DataClassJsonMixin):
    """A collection of nodes representing the solution tree."""

    nodes: list[Node] = field(default_factory=list)

    def __getitem__(self, idx: int) -> Node:
        return self.nodes[idx]

    def __len__(self) -> int:
        """Return the number of nodes in the journal."""
        return len(self.nodes)

    def append(self, node: Node) -> None:
        """Append a new node to the journal."""
        node.step = len(self.nodes)
        self.nodes.append(node)

    @property
    def draft_nodes(self) -> list[Node]:
        """Return a list of nodes representing intial coding drafts"""
        return [n for n in self.nodes if n.parent is None]

    @property
    def buggy_nodes(self) -> list[Node]:
        """Return a list of nodes that are considered buggy by the agent."""
        return [n for n in self.nodes if n.is_buggy]

    @property
    def good_nodes(self) -> list[Node]:
        """Return a list of nodes that are not considered buggy by the agent."""
        return [n for n in self.nodes if not n.is_buggy]

    def get_metric_history(self) -> list[float]:
        """Return a list of all metric values in the journal."""
        return [n.metric for n in self.nodes]

    def get_good_nodes(self) -> Node:
        return [n for n in self.nodes if not n.is_buggy]

    def get_best_node(self, only_good=True) -> None | Node:
        """Return the best solution found so far (node with the highest validation metric)."""
        if only_good:
            nodes = self.good_nodes
            if not nodes:
                return None
        else:
            nodes = self.nodes
        return max(nodes, key=lambda n: n.metric)

    def generate_summary(self, include_code: bool = False) -> str:
        """Generate a summary of the journal for the agent."""
        summary = []
        for n in self.good_nodes:
            summary_part = f"Design: {n.plan}\n"
            if include_code:
                summary_part += f"Code: {n.code}\n"
            summary_part += f"Results: {n.analysis}\n"
            summary_part += f"Validation Metric (Accuracy): {n.metric}\n"
            summary.append(summary_part)
        return "\n-------------------------------\n".join(summary)

"""### Agent"""

import random
from typing import Any, Callable, cast

import re
import sys
import json
import humanize

from pydantic import BaseModel

ExecCallbackType = Callable[[str, bool], ExecutionResult]



class Agent:
    def __init__(self, cfg, journal: Journal):
        super().__init__()
        self.cfg = cfg
        self.journal = journal
        self.data_preview: str | None = None

    def search_policy(self) -> Node | None:
        search_cfg = self.cfg.agent.search
        if len(self.journal.draft_nodes) < search_cfg.num_drafts:
            return None
        if random.random() < search_cfg.debug_prob:
            # Fix 2: Constrain debug attempts to max_debug_depth to avoid
            # getting stuck in local patch loops (refer AIDE paper Section 3.2)
            debuggable_nodes = [
                n for n in self.journal.buggy_nodes
                if n.is_leaf and n.debug_depth < search_cfg.max_debug_depth
            ]
            if debuggable_nodes:
                return random.choice(debuggable_nodes)
        good_nodes = self.journal.good_nodes
        if not good_nodes:
            return None
        return self.journal.get_best_node()

    def plan_and_code_query(self, system_message, user_message, temperature=0.0, retries=3):
        for _ in range(retries):
            response = generate_response(
                myModel,
                _messages=[
                    {'role': 'system', 'content': system_message},
                    {'role': 'user', 'content': user_message}
                ],
                temperature=temperature,
            )
            code = extract_code(response)
            nl_text = extract_text_up_to_code(response)
            if code:
                return nl_text, code
            print("Retrying...")
        return "", ""   # All retries failed; caller must handle empty code

    def _draft(self) -> Node:
        # ================  Draft Prompt ================
        system_prompt = """You are an expert ML engineer specializing in PyTorch image classification.

            CRITICAL RULES:
            1. Output ONLY a single ```python ... ``` code block. No explanations outside.
            2. MUST include ALL necessary imports at the top of the code:
               - import os
               - import json
               - import random
               - import numpy as np
               - import torch
               - import torch.nn as nn
               - import torch.optim as optim
               - from torch.utils.data import Dataset, DataLoader
               - from torchvision import models, transforms
               - from PIL import Image
            3. Choose an optimal random seed for reproducibility (common good seeds: 42, 123, 531, 999, 2024)
            4. Set ALL seeds: torch.manual_seed(), random.seed(), np.random.seed()
            5. LABEL must be INTEGER index (0-9), NOT one-hot, NOT string, NOT tensor.
            6. Dataset.__getitem__ for train/val: return img, class_to_idx[item['label']]
            7. Dataset.__getitem__ for test: return img, item['id'] (NO label access!)
            8. In Dataset.__init__, MUST store split folder explicitly as self.img_dir:
                def __init__(self, json_path, img_dir, transform, is_test=False):
                    self.data = json.load(open(json_path))
                    self.img_dir = img_dir   # store the image folder directly
                    self.transform = transform
                    self.is_test = is_test
              Then in __getitem__: img_path = os.path.join(self.img_dir, item['filename'])
            9. NEVER derive split name from json_path at runtime (self.json_path.split(...) is fragile).

            10. CrossEntropyLoss expects labels shape [batch_size] with int indices.
            11. ResNet18 fc input is 512, use model.fc.in_features, NEVER hardcode.
            12. pred.json output: MUST be a LIST of dicts: [{"id": 1878, "pred": "anon"}, ...]
            13. Image paths: os.path.join(data_dir, 'train'/'val'/'test', filename)
            14. transforms.Resize MUST be Resize((150, 150)) with a TUPLE, NOT Resize(150). Resize(150) only scales the shorter edge and produces inconsistent sizes that crash DataLoader.
            15. MUST print validation accuracy after each epoch in format: "Val Accuracy: XX.XX%"
        """

        user_prompt = f"""Task:{self.cfg.task_goal}
            Data Preview: {self.data_preview}

            COMMON MISTAKES TO AVOID:
            - DO NOT forget to import ALL required libraries (random, json, os, numpy, torch, etc.)
            - DO NOT use item['label'] for test set (test.json has no label field)
            - DO NOT use json.dump with generator - MUST use list: json.dump([{{"id": id, "pred": pred}} for ...], f)
            - DO NOT one-hot encode labels (CrossEntropyLoss expects int indices)
            - DO NOT hardcode model.fc = nn.Linear(155, 10) - use model.fc.in_features
            - DO NOT return torch.tensor(item['label']) when label is string
            - DO NOT forget to print "Val Accuracy: XX.XX%" after each epoch
            - DO NOT forget to set model.train() and model.eval() appropriately
            - DO NOT forget to save constructor arguments as class attributes (e.g., self.json_path = json_path) in Dataset __init__ before using them in __getitem__.
            - DO NOT use self.json_path.split('/') to infer folder — always pass img_dir explicitly.
        """

        plan, code = self.plan_and_code_query(
            system_message=system_prompt,
            user_message=user_prompt,
            temperature=0.7,
        )
        return Node(plan=plan, code=code)

    def _improve(self, parent_node: Node) -> Node:
        # ================ Improve Prompt ================
        system_prompt = """You are an expert ML engineer. Output ONLY a single ```python ... ``` code block.

        IMPROVEMENT RULE (AIDE atomic change principle):
        Make EXACTLY ONE atomic change from the list below. Do NOT combine multiple changes.
        Each iteration tests a single modification so its effect can be measured in isolation.

        CANDIDATE CHANGES (pick exactly one):
        1. Add a learning rate scheduler (CosineAnnealingLR or ReduceLROnPlateau)
        2. Add ONE new data augmentation technique (e.g., RandomErasing OR AugMix — not both)
        3. Unfreeze additional ResNet layers for fine-tuning
        4. Increase training epochs by 5 (e.g., 10 → 15)
        5. Add gradient clipping (nn.utils.clip_grad_norm_)
        6. Enable mixed precision training (torch.cuda.amp)
        7. transforms.Resize MUST be Resize((150, 150)) with a TUPLE, NOT Resize(150). Resize(150) only scales the shorter edge and produces inconsistent sizes that crash DataLoader.


        CRITICAL: Keep the training loop, keep printing "Val Accuracy: XX.XX%", keep correct pred.json format.
        """

        best_nodes = self.journal.good_nodes[-2:] if len(self.journal.good_nodes) >= 2 else self.journal.good_nodes
        history_lines = [f"Step {n.step}: val_acc={n.metric:.2%}" for n in best_nodes]

        user_prompt = f"""Task:
        {self.cfg.task_goal}

        Current best validation accuracy: {parent_node.metric:.2%}
        Recent attempts: {', '.join(history_lines)}

        Previous code summary: {parent_node.plan[:200] if parent_node.plan else 'N/A'}

        Please improve the accuracy by implementing ONE of the strategies above.
        Keep all the correct parts from previous code (label handling, path construction, output format).
        MUST include ALL imports at the top of the code.
        MUST still print "Val Accuracy: XX.XX%" after each epoch.
        """

        plan, code = self.plan_and_code_query(
            system_message=system_prompt,
            user_message=user_prompt,
            temperature=0.5,
        )
        return Node(plan=plan, code=code, parent=parent_node)

    def _debug(self, parent_node: Node) -> Node:
        # ================  Debug Prompt ================
        system_prompt = """You are an expert ML engineer fixing buggy PyTorch code. Output ONLY a single ```python ... ``` code block.

        DEBUGGING CHECKLIST:
        1. Check ALL imports are present (os, json, random, numpy, torch, nn, optim, Dataset, DataLoader, models, transforms, Image)
        2. Label shape: labels must be [batch_size] with int indices, NOT [batch_size, 10]
        3. Label type: must be LongTensor, not FloatTensor
        2. Image paths: must include split folder (train/val/test)
        3. test.json: DO NOT access item['label'] - it doesn't exist
        4. Output pred.json: MUST be LIST of dicts [{"id": int, "pred": str}, ...]
        5. Model fc: use model.fc.in_features, not hardcoded number
        6. DO NOT load pre-saved models - MUST train from scratch
        7. MUST print "Val Accuracy: XX.XX%" after each epoch
        8. transforms.Resize MUST be Resize((150, 150)) with a TUPLE, NOT Resize(150). Resize(150) only scales the shorter edge and produces inconsistent sizes that crash DataLoader.
        9. AttributeError in Dataset: ensure variables like json_path or data_dir are properly assigned as self.xxx in __init__ before using them in __getitem__.

        """

        user_prompt = f"""Task:
        {self.cfg.task_goal}

        Buggy Code:
        {wrap_code(parent_node.code)}

        Error Message:
        {wrap_code(parent_node.term_out, lang='')}

        Data Preview:
        {self.data_preview}

        Please fix ALL bugs. Provide COMPLETE fixed code, not just changed parts.
        Most common issue: label handling in Dataset.__getitem__ or loss computation.
        MUST still print "Val Accuracy: XX.XX%" after each epoch.
        """

        plan, code = self.plan_and_code_query(
            system_message=system_prompt,
            user_message=user_prompt,
            temperature=0.1,
        )
        return Node(plan=plan, code=code, parent=parent_node)

    def update_data_preview(self):
        self.data_preview = data_preview_generate(cfg.data_dir)

    def step(self, exec_callback: ExecCallbackType):
        if not self.journal.nodes or self.data_preview is None:
            self.update_data_preview()

        parent_node = self.search_policy()

        if parent_node is None:
            print("📝 階段：Draft（生成初始程式碼）")
            result_node = self._draft()
        elif parent_node.is_buggy:
            print(f"🐛 階段：Debug（修復 Step {parent_node.step} 的錯誤，深度 {parent_node.debug_depth}）")
            result_node = self._debug(parent_node)
        else:
            print(f"🚀 階段：Improve（改進 Step {parent_node.step}，目前準確率 {parent_node.metric:.2%}）")
            result_node = self._improve(parent_node)

        print("⚙️  正在執行生成的程式碼...")

        # Guard: LLM failed to produce valid Python after all retries
        if not result_node.code.strip():
            result_node.is_buggy = True
            result_node.metric = 0.0
            result_node.analysis = "LLM failed to produce a valid Python code block after all retries."
            print("📊 結果：❌ Buggy（LLM 未產生有效程式碼）")
            self.journal.append(result_node)
            return

        self.parse_exec_result(
            node=result_node,
            exec_result=exec_callback(result_node.code, True),
        )
        print(f"📊 結果：{'❌ Buggy' if result_node.is_buggy else f'✅ 準確率 {result_node.metric:.2%}'}")
        self.journal.append(result_node)

    def parse_exec_result(self, node: Node, exec_result: ExecutionResult):
        node.absorb_exec_result(exec_result)

        if node.exc_type is not None:
            node.is_buggy = True
            node.metric = 0.0
            # Skip LLM analysis for errors — too slow on local GPU.
            # The raw error in term_out is passed to _debug() anyway.
            node.analysis = f"Runtime error: {node.exc_type}. Last output: {node.term_out[-500:]}"
            return

        import re
        matches = re.findall(r"[Vv]al(?:idation)?\s+[Aa]cc(?:uracy)?[:\s]+([0-9]+\.?[0-9]*)", node.term_out)
        if matches:
            node.metric = float(matches[-1]) / 100 if float(matches[-1]) > 1 else float(matches[-1])
            node.is_buggy = False
            # Skip LLM summary — too slow. Simple string is enough for improve prompts.
            node.analysis = f"Val accuracy: {node.metric:.2%}. Output tail: {node.term_out[-300:]}"
        else:
            node.is_buggy = True
            node.metric = 0.0
            node.analysis = "Could not extract val accuracy from output."

"""### Text Processing"""

import json
import re

def wrap_code(code: str, lang="python") -> str:
    """Wraps code with three backticks."""
    return f"```{lang}\n{code}\n```"


def is_valid_python_script(script):
    """Check if a script is a valid Python script."""
    try:
        compile(script, "<string>", "exec")
        return True
    except SyntaxError:
        return False


def extract_jsons(text):
    """Extract all JSON objects from the text. Caveat: This function cannot handle nested JSON objects."""
    json_objects = []

    # Find {} by regular expression
    matches = re.findall(r"\{.*?\}", text, re.DOTALL)

    # Try to transform string into json objects
    for match in matches:
        try:
            json_obj = json.loads(match)
            json_objects.append(json_obj)
        except json.JSONDecodeError:
            pass

    return json_objects

def trim_long_string(string, threshold=5100, k=2500):
    # Check if the length of the string is longer than the threshold
    if len(string) > threshold:
        # Output the first k and last k characters
        first_k_chars = string[:k]
        last_k_chars = string[-k:]

        truncated_len = len(string) - 2 * k

        return f"{first_k_chars}\n ... [{truncated_len} characters truncated] ... \n{last_k_chars}"
    else:
        return string

def extract_code(text):
    """Extract python code blocks from the text."""
    parsed_codes = []

    # When code is in a text or python block
    matches = re.findall(r"```(python)?\n*(.*?)\n*```", text, re.DOTALL)
    for match in matches:
        code_block = match[1]
        parsed_codes.append(code_block)

    # When the entire text is code or backticks of the code block is missing
    if len(parsed_codes) == 0:
        matches = re.findall(r"^(```(python)?)?\n?(.*?)\n?(```)?$", text, re.DOTALL)
        if matches:
            code_block = matches[0][2]
            parsed_codes.append(code_block)

    # validate the parsed codes
    valid_code_blocks = [
        c for c in parsed_codes if is_valid_python_script(c)
    ]
    # 加這行 debug
    print(f"[extract_code] 找到 {len(parsed_codes)} 個 block，有效 {len(valid_code_blocks)} 個，原文前100字: {text[:100]!r}")

    return "\n\n".join(valid_code_blocks)

def extract_text_up_to_code(s):
    """Extract (presumed) natural language text up to the start of the first code block."""
    if "```" not in s:
        return ""
    return s[: s.find("```")].strip()

"""**Dataset Preview**"""

def preview_json(p: Path) -> str:
    """Generate a textual preview of a json file"""

    try:
        with open(p, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        return f"ERROR: {p.name} is not valid JSON - {e}"
    except FileNotFoundError:
        return f"ERROR: {p.name} not found at {p}"
    except Exception as e:
        return f"ERROR: {p.name} - {e}"

    out = []
    num_items = len(data)
    out.append(f"-> {p.name} contains a list with {num_items} items.")

    if num_items == 0:
        out.append("WARNING: This JSON file is empty!")
        return "\n".join(out)

    first_item = data[0]
    keys = list(first_item.keys())

    # ================ TODO 1: Tell LLM agents the structure of json file ================
    folder_mapping = {
        "train.json": "train/",
        "val.json": "val/",
        "test.json": "test/"
    }
    folder_name = folder_mapping.get(p.name, "")
    if folder_name:
        out.append(f"Images are in: os.path.join(data_dir, '{folder_name}', item['filename'])")


    if p.name == "test.json":
        out.append("CRITICAL: test.json does NOT have 'label' field. Do NOT access item['label'] for test set.")
    else:
        out.append(f"Label format: item['label'] is a STRING (e.g., 'tomori'), must convert to integer index using class_to_idx dict")
    # ====================================================================================

    out.append(f"Keys in each item: {', '.join(keys)}")
    out.append("Example of the first item:")
    out.append(json.dumps(first_item, indent=2, ensure_ascii=False))

    return "\n".join(out)

def data_preview_generate(base_path):
    """Generate a textual preview of a directory"""
    result = []
    files = [p for p in Path(base_path).glob("*.json")]

    for f in sorted(files):
        result.append(preview_json(f))

    return "\n\n".join(result)

"""## Config"""

import torch
import random
import numpy as np

# DO NOT MODIFY THIS CLASS
class Config:
    """
    A recursive configuration class that converts a dictionary into an object
    with attributes accessible using dot notation.
    """

    def __init__(self, dictionary):
        for key, value in dictionary.items():
            if isinstance(value, dict):
                value = Config(value)
            setattr(self, key, value)

def set_seed(seed=531):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

set_seed()

config = {
    "exp_name": "ML2026SPRING_HW2",
    "data_dir": Path("./hw2_data").resolve(),

    "task_goal": """10-class anime idol image classification (150x150 PNG).

Classes: tomori, anon, soyo, taki, rana, sakiko, nyamuchi, umiri, uika, mutsumi

Directory structure (CRITICAL):
  ./hw2_data/train/      <- images for train.json
  ./hw2_data/val/        <- images for val.json
  ./hw2_data/test/       <- images for test.json

JSON files:
  train.json: [{"id": int, "filename": "410.png", "label": "tomori"}, ...]
  val.json:   same format as train.json
  test.json:  [{"id": int, "filename": "1878.png"}, ...]  <- NO label field!

Label Processing (MOST CRITICAL):
  CLASSES = ['tomori','anon','soyo','taki','rana','sakiko','nyamuchi','umiri','uika','mutsumi']
  class_to_idx = {c: i for i, c in enumerate(CLASSES)}

  In Dataset.__getitem__ for train/val:
    label = class_to_idx[item['label']]  # Returns INTEGER, NOT tensor, NOT one-hot
    return img, label  # label shape: scalar int, DataLoader batches to [batch_size]

  In Dataset.__getitem__ for test:
    return img, item['id']  # NO label access!

  CrossEntropyLoss expects:
    - outputs: shape [batch_size, 10]
    - labels: shape [batch_size] with integer class indices (0-9)
    - NEVER one-hot encode labels!
    - NEVER return torch.tensor(item['label']) if label is string!

Model:
  - ResNet18 pretrained (weights=ResNet18_Weights.IMAGENET1K_V1)
  - Replace fc: num_features = model.fc.in_features; model.fc = nn.Linear(num_features, 10)
  - NEVER hardcode fc input size (e.g., 155 is WRONG, should be 512 for ResNet18)
  - DO NOT load pre-saved models - TRAIN FROM SCRATCH

Seed Strategy:
  - Use torch.manual_seed(531) as base seed
  - Also set: random.seed(531), np.random.seed(531)
  - If you know a better seed for image classification, you can try it
  - Common good seeds: 42, 123, 999, 2024, 777, 1004

Training:
  - Adam lr=1e-4, CrossEntropyLoss, batch=32, epochs=10
  - Train augmentation: RandomHorizontalFlip, RandomRotation(15), ColorJitter
  - Val/Test: Only Resize + ToTensor + Normalize
  - Print validation accuracy after each epoch in format: "Val Accuracy: XX.XX%"

Output:
  - **SAVE** to ./pred.json
  - Format: [{"id": 1878, "pred": "anon"}, ...]  <- LIST of dicts, NOT generator!
  - pred MUST be string (idol name), NOT integer index

Seed: torch.manual_seed(531) for reproducibility
""",

    "agent": {
        "steps": 5,
        "search": {
            "debug_prob": 0.7,
            "num_drafts": 2,
            "max_debug_depth": 3,
        },
    },
}

#set_seed(531)
cfg = Config(config)

"""## Main"""

def main():

    def exec_callback(*args, **kwargs):
        res = interpreter.run(*args, **kwargs)
        return res

    journal = Journal()
    agent = Agent(
        cfg=cfg,
        journal=journal,
    )

    interpreter = Interpreter()

    global_step = len(journal)
    while global_step < cfg.agent.steps:
        print(f"\n========== 正在執行 Step {global_step} ==========")
        print("🤖 Agent 正在思考與生成程式碼/除錯中...")
        # run agent
        agent.step(exec_callback=exec_callback)
        print("✅ 程式碼執行完畢，正在儲存結果...")

        # save results for this iteration
        save_run(cfg, journal)
        # get currect step
        global_step = len(journal)


    # Kill created child process
    interpreter.cleanup_session()


    # --- main agent loop (still inside the same __main__ guard) ---
    main()

# Get your best result!

"""# References
The code scripts are from [aideml](https://github.com/WecoAI/aideml) project on github with some modifications.

AIDE: AI-Driven Exploration in the Space of Code
https://arxiv.org/pdf/2502.13138

"""
